services:
  seaweedfs:
    image: chrislusf/seaweedfs
    container_name: osrs-seaweed
    ports:
      - "8333:8333"
      - "9333:9333"
      - "8888:8888"
      - "23646:23646"
    volumes:
      - weed-data:/data
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      S3_BUCKET: ${S3_BUCKET}
volumes:
  weed-data:
